# This is a basic workflow that is manually triggered

name: CSV Check

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fileTest"
  fileTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Default action to add
      - uses: actions/checkout@v2
      # Add JDK 11
      - uses: actions/setup-java@v1
        with: 
          java-version: '11'
      - run: ./gradlew utfUnitTest
    
