# This is a basic workflow that is manually triggered

name: CSV Check

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  file_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - run: echo "Checking input file if it is CSV UTF-8"
    - uses: actions/checkout@v2
    - run: java utfUnitTest.java
    - run: echo "File is most likely CSV UTF-8"
